from __future__ import annotations

"""
Centralized vocabulary for fact names.

Naming scheme: ENTITY__FEATURE__STATE
"""

## === WNT PATHWAY VOCABULARY ===

# Wnt ligand / receptor / pathway components
WNT_LIGAND_PRESENT = "WNT__LIGAND__PRESENT"
WNT_STATE_OFF = "WNT__STATE__OFF"

LRP6_PROTEIN_PRESENT = "LRP6__PROTEIN__PRESENT"
LRP6_SER_SITES_INTACT = "LRP6__SER_SITES__INTACT"
LRP6_SER_SITES_P = "LRP6__SER_SITES__P"
LRP6_SIGNALING_ACTIVE = "LRP6__SIGNALING__ACTIVE"

# Frizzled receptor
FRIZZLED_PROTEIN_PRESENT = "FRIZZLED__PROTEIN__PRESENT"

# Wnt signalosome state
SIGNALOSOME_STATE_FORMED = "SIGNALOSOME__STATE__FORMED"

# Destruction complex activity
DESTRUCTION_COMPLEX_ACTIVITY_HIGH = "DESTRUCTION_COMPLEX__ACTIVITY__HIGH"
DESTRUCTION_COMPLEX_ACTIVITY_LOW = "DESTRUCTION_COMPLEX__ACTIVITY__LOW"

# β-catenin states
BETA_CAT_LEVEL_BASELINE = "BETA_CAT__LEVEL__BASELINE"
BETA_CAT_LEVEL_UP = "BETA_CAT__LEVEL__UP"
BETA_CAT_LEVEL_DOWN = "BETA_CAT__LEVEL__DOWN"

# Mutations (abstract, generic)
LRP6_SER_SITES_MUTATED = "LRP6__SER_SITES__MUTATED"



# === PI3K/AKT PATHWAY VOCABULARY ===

# Receptor tyrosine kinase and ligand
RTK_RECEPTOR_PRESENT = "RTK__RECEPTOR__PRESENT"
GROWTH_FACTOR_LIGAND_PRESENT = "GROWTH_FACTOR__LIGAND__PRESENT"
GROWTH_FACTOR_STATE_OFF = "GROWTH_FACTOR__STATE__OFF"

# PI3K state
PI3K_STATE_ACTIVE = "PI3K__STATE__ACTIVE"

# AKT phosphorylation and activity
AKT_PHOSPHO_THR308_P = "AKT__PHOSPHO_THR308__P"
AKT_PHOSPHO_SER473_P = "AKT__PHOSPHO_SER473__P"
AKT_STATE_ACTIVE = "AKT__STATE__ACTIVE"
AKT_STATE_INACTIVE = "AKT__STATE__INACTIVE"

# GSK3 state (simplified as ON/OFF)
GSK3_STATE_ACTIVE = "GSK3__STATE__ACTIVE"
GSK3_STATE_INACTIVE = "GSK3__STATE__INACTIVE"

# Apoptotic tendency (very coarse-grained)
APOPTOSIS_TENDENCY_HIGH = "APOPTOSIS__TENDENCY__HIGH"
APOPTOSIS_TENDENCY_LOW = "APOPTOSIS__TENDENCY__LOW"
